
import Menu from "../components/Menu";
import RestaurantNavBar from "../components/RestaurantNavBar";
import type { Metadata } from "next";


export const metadata: Metadata = {
  title: "menu -  restaurant ",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <>
      <div className="bg-white w-[100%] rounded p-3 shadow">
        <RestaurantNavBar />

        <Menu />
      </div>
    </>
  );
};

export default page;
