import React from "react";
import NavBar from "../components/NavBar";
import Header from "./components/Header";
import RestauranCard from "./components/RestauranCard";
import SearchSideBar from "./components/SearchSideBar";
import type { Metadata } from "next";


export const metadata: Metadata = {
  title: "Search restaurant ",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <>
  
      <Header />
      <div className="flex py-4 m-auto w-2/3 justify-between items-start">
  
        <SearchSideBar />

        <div className="w-5/6">
          <RestauranCard />
        </div>
      </div>
    </>
  );
};

export default page;
