
import Form from "./components/Form";
import Header from "./components/Header";

import type { Metadata } from "next";


export const metadata: Metadata = {
  title: "Reserve -  restaurant ",
  description: "Generated by create next app",

};
//FNlns6vLxOYrA1fX
const page = () => {
  return (
    <div className="border-t h-screen">
      <div className="py-9 w-3/5 m-auto">
        <Header />
        {/* FORM */}
        <Form />
      </div>
    </div>
  );
};

export default page;
