import React from "react";
import NavBar from "../../components/NavBar";
import Description from "./components/Description";
import Header from "./components/Header";
import Images from "./components/Images";
import Rating from "./components/Rating";
import ReservationCard from "./components/ReservationCard";
import RestaurantNavBar from "./components/RestaurantNavBar";
import Reviews from "./components/Reviews";
import Title from "./components/Title";
import type { Metadata } from "next";
import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

export const metadata: Metadata = {
  title: "moz -  restaurant ",
  description: "Generated by create next app",
};

const fetchRestaurantBySlug:any = async (slug: string) => {
  return await prisma.restaurant.findUnique({
    where: {
      slug,
    },
    select:{
      id:true,
      name:true,
      images:true,
      description:true,
      slug:true
    }
  });
};

const page = async ({ params }: { params: { slug: string } }) => {
  const restaurant = await fetchRestaurantBySlug(params?.slug);
  return (
    <>
      <div className="bg-white w-[70%] rounded p-3 shadow">
        <RestaurantNavBar slug={restaurant?.slug} />
        <Title name={restaurant?.name}/>
        <Rating />
        <Description description={restaurant?.description} />
        <Images images={restaurant?.images} />

        <Reviews />
      </div>
      <div className="w-[27%] relative text-reg">
        <ReservationCard />
      </div>
    </>
  );
};

export default page;
